### ISSUE TITLE
Undocumented proposals and statements

### ISSUE THREAD

**Issue by Pl-Mrcy** [csharrison/aggregate-reporting-api#20]
Hi @csharrison,

Many of the topics we discussed in the recent "WICG Conversion Measurement API" meetings are not documented in publicly available GitHub repositories.
It includes the app-to-web attribution proposal that you presented on Monday (2021-03-22) and the aggregation proposal that you presented the week before (2021-03-15). It also includes information that you give us answering questions (willingness to support lift measurement, etc.)
While most of this information is accessible in the meeting minutes, I think that we would benefit a lot from having all this formalized in an actual GitHub proposal.

Do you intend to write something down to that effect?

Thank you very much!

**Comment by csharrison** [comment]
Hey Paul did you mean to open this comment in the conversion measurement repo? That's currently what the scope of those meetings are about.

 - App to web attribution we published inhttps://github.com/WICG/conversion-measurement-api/blob/main/app_to_web.md
 - VTC is mentioned in the aggregate explainer: https://github.com/WICG/conversion-measurement-api/blob/main/AGGREGATE.md#view-through-conversions-1 and there are a few issues about how we could support it in the event-level API (https://github.com/WICG/conversion-measurement-api/issues/98, https://github.com/WICG/conversion-measurement-api/issues/84). We are working on publishing more about this soon.
 - The aggregation proposals are in issues right now (https://github.com/WICG/conversion-measurement-api/issues/116). I am hoping we can finalize these decisions soon and publish a follow-up.

Let's re-open issues on the conversion github if there is something that needs more documentation, since this repo is about a different API.
